
[tool.poetry]
name = 'logdna'
version = '1.5.2'
description = 'A Python Package for Sending Logs to LogDNA'
authors = ['LogDNA Inc.']
license = 'MIT'

[tool.poetry.dependencies]
requests = "^2.7.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
