version: 2
jobs:
  publish:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run:
          name: Check Tagged Push
          command: |
            TAG_VERSION=$(git tag -l --sort=-v:refname | head -n 1 | cut -d'-' -f2)
            PKG_VERSION=$(cat logdna/_version.py | grep "__version__ = " | cut -d'=' -f2 | cut -d"'" -f2)
            PKG_VERSION_TOML=$(cat pyproject.toml | grep "version = " | cut -d'=' -f2 | cut -d"'" -f2)

            if [[ "${TAG_VERSION}" != "${PKG_VERSION}" ] -a ["${TAG_VERSION}" != "${PKG_VERSION_TOML}"]]; then
              echo "There is mismatch:"
              echo "  TAG_VERSION: ${TAG_VERSION}"
              echo "  PKG_VERSION: ${PKG_VERSION}"
              echo "  PKG_VERSION_TOML: ${PKG_VERSION_TOML}"
              exit 1
            fi
      - run:
          name: Publish
          command: |
            curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
            poetry build
            twine upload dist/*.tar.gz
workflows:
  version: 2
  update_package:
    jobs:
      - publish:
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?/
            branches:
              ignore: /.*/
